### PR TITLE
Examples refactor

### PR DESCRIPTION
**Pull request by dgahle**
I have found a number of errors across running the examples. These errors range from dividing by zeros errors, figures not loading, and missing input data. 

I am iteratively going through the examples to get them to run on my machine. Hopefully, make them more agnostic to who ever is running the examples, thus making them more useful and ColRadPy more accessible.

### CODE REVIEW

**Comment by dgahle** [comment]
Where the ADF04 files for ion_bal.py modified? The update I have done scrapes them from Open-ADAS but now I get the following ColRadPy error:

```
Traceback (most recent call last):
  File "C:/Users/dsgah/github/ColRadPy/examples/ion_bal.py", line 86, in <module>
    ion_0.solve_time_independent()
  File "C:\Users\dsgah\github\ColRadPy\colradpy\ionization_balance_class.py", line 607, in solve_time_independent
    self.data['processed']['eigen_vec'] = solve_matrix_exponential_steady_state(
  File "C:\Users\dsgah\github\ColRadPy\colradpy\solve_matrix_exponential.py", line 117, in solve_matrix_exponential_steady_state
    ev = eigenvectors.transpose(0,1,3,2)[index]#egienvectors sorted on eigenvals
ValueError: could not broadcast input array from shape (1,10) into shape (1,1)
```

**Comment by dgahle** [comment]
RuntimeWarning in populating_lvls_example.py (below). I would be happy to look into these in the future but as a separate task (might be an issue with the contribution of high levels, see figure). Here I am just trying to get the examples running, scraping all the required input, and writing the output to disk.

```
C:\Users\dsgah\github\ColRadPy\colradpy\colradpy_class.py:1178: RuntimeWarning: divide by zero encountered in double_scalars
  self.data['processed']['wave_vac'].append(1.e7/abs(self.data['atomic']['energy'][levels_to_keep[j]]\
```

image

**Comment by dgahle** [comment]
I got a two RuntimeWarning and one VisibleDeprecationWarning when running `split_multiplet_example.py` (again a task for another time).

```
ECIP was not previously calculated, calculating now from inside 'suppliment_with_ecip'
C:\Users\dsgah\github\ColRadPy\colradpy\colradpy_class.py:1178: RuntimeWarning: divide by zero encountered in double_scalars
  self.data['processed']['wave_vac'].append(1.e7/abs(self.data['atomic']['energy'][levels_to_keep[j]]\
C:\Users\dsgah\github\ColRadPy\colradpy\nist_read_txt.py:5: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  tmp = np.genfromtxt(path+el.lower()+'_'+str(ch),dtype=None,delimiter=',')
C:\Users\dsgah\github\ColRadPy\colradpy\colradpy_class.py:1980: RuntimeWarning: invalid value encountered in double_scalars
  if( (np.abs(float(tmp[0]['energy'])-self.data['atomic']['energy'][int(self.data['processed']['split']['term_map'][i])])/tmp[0]['energy'] < fractional_diff_adf04_nist) or
```

**Comment by dgahle** [comment]
`numpy.core._exceptions.MemoryError: Unable to allocate 5.70 GiB for an array with shape (60000, 10, 49, 26) and data type float64`

This was a funny error to get running `ss_ion_bal_adf11.py` (full traceback below). Reducing the size of `temp_grid` made no difference. If this really is innate to the calculation then `README.md` really needs to describe the computational resource needed to do different things. 

I am guessing some of the dimensions for `(60000, 10, 49, 26)` are (time?, Te, ?, charge state)

```
Traceback (most recent call last):
  File "C:/Users/dsgah/github/ColRadPy/examples/ss_ion_bal_adf11.py", line 65, in <module>
    ion = ionization_balance(fils, #a text array of the files used for the ionization balance
  File "C:\Users\dsgah\github\ColRadPy\colradpy\ionization_balance_class.py", line 143, in __init__
    adf11 = read_adf11(fils[i])
  File "C:\Users\dsgah\github\ColRadPy\colradpy\read_adf11.py", line 52, in read_adf11
    adf11['input_file'][str(i)] = np.zeros((adf11['input_file']['metas'][i],
numpy.core._exceptions.MemoryError: Unable to allocate 5.70 GiB for an array with shape (60000, 10, 49, 26) and data type float64

Process finished with exit code 1
```

**Comment by dgahle** [comment]
> ss_ion_bal_adf11.py

I get the same error for `td_ion_bal_adf11.py` as you can imagine: `numpy.core._exceptions.MemoryError: Unable to allocate 5.70 GiB for an array with shape (60000, 10, 49, 26) and data type float64`.

**Comment by dgahle** [comment]
> `numpy.core._exceptions.MemoryError: Unable to allocate 5.70 GiB for an array with shape (60000, 10, 49, 26) and data type float64`
> 
> This was a funny error to get running `ss_ion_bal_adf11.py` (full traceback below). Reducing the size of `temp_grid` made no difference. If this really is innate to the calculation then `README.md` really needs to describe the computational resource needed to do different things.
> 
> I am guessing some of the dimensions for `(60000, 10, 49, 26)` are (time?, Te, ?, charge state)
> 
> ```
> Traceback (most recent call last):
>   File "C:/Users/dsgah/github/ColRadPy/examples/ss_ion_bal_adf11.py", line 65, in <module>
>     ion = ionization_balance(fils, #a text array of the files used for the ionization balance
>   File "C:\Users\dsgah\github\ColRadPy\colradpy\ionization_balance_class.py", line 143, in __init__
>     adf11 = read_adf11(fils[i])
>   File "C:\Users\dsgah\github\ColRadPy\colradpy\read_adf11.py", line 52, in read_adf11
>     adf11['input_file'][str(i)] = np.zeros((adf11['input_file']['metas'][i],
> numpy.core._exceptions.MemoryError: Unable to allocate 5.70 GiB for an array with shape (60000, 10, 49, 26) and data type float64
> 
> Process finished with exit code 1
> ```

So running this with more RAM I get a different error... `IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`. 

The full traceback is:
```
/Users/daljeet-singh-gahle/opt/anaconda3/envs/ColRadPy/bin/python /Users/daljeet-singh-gahle/github/ColRadPy/examples/ss_ion_bal_adf11.py 
/Users/daljeet-singh-gahle/github/ColRadPy/colradpy/solve_matrix_exponential.py:117: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ev = eigenvectors.transpose(0,1,3,2)[index]#egienvectors sorted on eigenvals
Traceback (most recent call last):
  File "/Users/daljeet-singh-gahle/github/ColRadPy/examples/ss_ion_bal_adf11.py", line 72, in <module>
    ion.solve_time_independent()#solve the ionization balance matrix in steady state
  File "/Users/daljeet-singh-gahle/github/ColRadPy/colradpy/ionization_balance_class.py", line 607, in solve_time_independent
    self.data['processed']['eigen_vec'] = solve_matrix_exponential_steady_state(
  File "/Users/daljeet-singh-gahle/github/ColRadPy/colradpy/solve_matrix_exponential.py", line 117, in solve_matrix_exponential_steady_state
    ev = eigenvectors.transpose(0,1,3,2)[index]#egienvectors sorted on eigenvals
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Review by johnson-c — APPROVED** [review]
Hi Daljeet, thanks for taking the time to improve these examples. Everything works great, sorry I took so much time to merge this.

**Pull request merged**
